---
abstract: 'Catalyst based application'
author:
  - 'Catalyst developer'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Finance-HostedTrader-UI
no_index:
  directory:
    - t
    - inc
requires:
  CPAN: 0
  Catalyst::Action::RenderView: 0
  Catalyst::Model::DBIC::Schema: 0
  Catalyst::Plugin::ConfigLoader: 0
  Catalyst::Plugin::Static::Simple: 0
  Catalyst::Runtime: 5.80013
  Catalyst::View::TT: 0
  Config::General: 0
  ExtUtils::MakeMaker: 6.42
  File::Copy::Recursive: 0
  Finance::HostedTrader: 0
  JSON: 0
  parent: 0
version: 0.02
