package Finance::HostedTrader::UI::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'Finance::HostedTrader::UI::Schema',
    
    connect_info => {
        dsn => 'dbi:mysql:fx',
        user => 'fxhistor',
        password => '',
        AutoCommit => q{1},
    }
);

=head1 NAME

Finance::HostedTrader::UI::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Finance::HostedTrader::UI>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Finance::HostedTrader::UI::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.29

=head1 AUTHOR

A clever guy

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
